backend:
  name: git-gateway
  repo: khorawajatin/jekyll-to-netlify
  branch: master

media_folder: "img"

collections: 
  - name: "website-settings"
    label: "Website Settings"
    files:
      - label: "Website Settings"
        name: "site"
        file: "_data/siteinfo.yml"
        fields: 
          - label: "Tel"
            name: "tel"
            widget: "string"